---
# tasks file for tomcat

- name: Install basic software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk
    - curl
    - wget


- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz dest=/opt/apache-tomcat-8.5.9.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.9.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.9

- name: Symlink install directory
  file: src=/opt/apache-tomcat-8.5.9 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes
#
#- name: Configure Tomcat server
  #template: src=server.xml dest=/usr/share/tomcat/conf/
  #notify: restart tomcat

#- name: Configure Tomcat users
  #template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  #notify: restart tomcat

- name: Install Tomcat systemd script
  copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service mode=0700

- name: Reload demon
  command: systemctl daemon-reload

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes
